name: grid_testing_001
favicon: null
layout_spectrum: 0.99608
typography_spectrum: 0.26574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#443f3b'
    - '#716a64'
    - '#fefdf8'
    - '#e6d8d0'
    - '#a1948c'
  brandStrength: 1
  lightness: 0.13423298788256943
  saturation: 0.9375
  rhythmicContrast: 0.8724506760481745
purpose: []
