name: grid_testing_001
favicon: null
layout_spectrum: 0.2712698895484209
typography_spectrum: 0.8652323917485774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.22454086155630648
  lightness: 0.13423298788256943
  saturation: 0.8760509490966797
  rhythmicContrast: 0.8724506760481745
purpose: []
